server:
  port: 3002

spring:
  application:
    name: cuner-oauth2-authresource
  # redis
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms


management:
  endpoints:
    web:
      exposure:
        include: '*'     # \u914D\u7F6Eactuator\u76D1\u63A7