server:
  port: 3001

spring:
  application:
    name: cuner-oauth2-authserver
  # redis
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis-plus:
  global-config:
    db-config:
      id-type: none
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'     # 配置actuator监控


