server:
  port: 1001

spring:
  application:
    name: cuner-hystrix-turbine # 注册到Eureka的应用名称

eureka:                # 注册到Eureka
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: cuner-hystrix-turbine1001
    prefer-ip-address: true
turbine:
  app-config: cuner-sys-consumer
  cluster-name-expression: "'default'"
