server:
  port: 3005
  servlet:
    session:
      cookie:
        name: client2 # 必须设置，否则单点登录时一直跳转到认证服务的login页

spring:
  application:
    name: cuner-oauth2-sso-client2

security:
  oauth2:
    client:
      client-id: cuner-oauth2-authresource
      client-secret: 123456
      user-authorization-uri: http://localhost:3001/oauth/authorize
      access-token-uri: http://localhost:3001/oauth/token
    resource:
      user-info-uri: http://localhost:3002/getCurUser

